" Basic appearance
color desert
syntax on
set number
set relativenumber
set ruler
set hlsearch
set nolinebreak
autocmd BufNewFile,BufRead *.md setf markdown

" Indent with 4 spaces
set shiftwidth=4
set tabstop=4
set expandtab
set smartindent
set autoindent

" Remaps 
inoremap jk <Esc>

" File-specific remaps
augroup file_remaps
    autocmd!
    autocmd BufWinEnter *.tex nnoremap <F3> :w<CR>:!pdflatex %:p<CR>
    autocmd BufWinEnter *.md nnoremap <F3> :w<CR>:!pandoc "%:p" -o "%:p:h/%:r.pdf"<CR>
augroup END

" Folding
set foldcolumn=1
set foldmethod=manual
augroup AutoSaveFolds
    autocmd!
    autocmd BufWinLeave ?* mkview
    autocmd BufWinEnter ?* silent loadview
    autocmd BufWinEnter ?* normal zR
augroup END

" Spellcheck mode <F4>
nnoremap <F4> :call Toggle_spell()<CR>
function Toggle_spell()
    if &l:spell
        set nospell
        echom "Spell OFF"
    else
        set spell spelllang=en_gb
        echom "Spell ON"
    endif
endfunction

" Essay mode <F5>
nnoremap <F5> :call Toggle_essay()<CR>
function Toggle_essay()
    if &l:linebreak
        setlocal textwidth=999
        setlocal nolinebreak
        normal! gggqG<C-o><C-o>
        set nospell
        echom "Essay: OFF"
    else
        setlocal textwidth=80
        setlocal linebreak
        normal! gggqG<C-o><C-o>
        setlocal spell spelllang=en_gb
        echom "Essay: ON"
    endif
endfunction

" Encrypt <F6>
nnoremap <F6> :call Encrypt()<CR>
function Encrypt()
    set cryptmethod=blowfish2
    exec "X"
endfunction

" File templates
augroup templates
    autocmd!
    autocmd BufNewFile *.asm 0r ~/.vim/templates/skeleton.asm
    autocmd BufNewFile [^(min)]*\.tex 0r ~/.vim/templates/skeleton.tex
    autocmd BufNewFile *.min.tex 0r ~/.vim/templates/skeleton.min.tex
    autocmd BufNewFile *.html 0r ~/.vim/templates/skeleton.html
    autocmd BufNewFile *.md 0r ~/.vim/templates/skeleton.md
augroup END

" vim-plug
call plug#begin('~/.local/share/nvim/plugged')

Plug 'xuhdev/vim-latex-live-preview', {'for': 'tex'}
let g:livepreview_previewer = 'okular'
set updatetime=1000

Plug 'leafgarland/typescript-vim', {'for': 'typescript'}

call plug#end()
