" Basic appearance
color desert
syntax on
set number
set relativenumber
set ruler
set hlsearch
set nolinebreak
set list
set listchars=tab:›\ ,trail:⋅
set tw=80

" Indent with 4 spaces
set shiftwidth=4
set tabstop=4
set expandtab
set smartindent
set autoindent

" Folding
set foldcolumn=1
set foldmethod=manual
augroup AutoSaveFolds
    autocmd!
    autocmd BufWinLeave ?* mkview
    autocmd BufWinEnter ?* silent loadview
    autocmd BufWinEnter ?* normal zR
augroup END

" Remaps 
inoremap jk <Esc>
noremap <Up>    :resize +5 <CR>
noremap <Down>  :resize -5 <CR>
noremap <Left>  :vertical resize -5 <CR>
noremap <Right> :vertical resize +5 <CR>

" File-specific stuff
autocmd BufNewFile,BufRead *.md setf markdown

" File-specific remaps
augroup file_remaps
    autocmd!
    autocmd BufWinEnter *.tex nnoremap <F3> :w<CR>:!pdflatex %:p<CR>
    autocmd BufWinEnter *.md nnoremap <F3> :w<CR>:!pandoc "%:p" -o "%:p:h/%:r.pdf"<CR>
augroup END


" Spellcheck mode <F4>
nnoremap <F4> :call Toggle_spell()<CR>
function Toggle_spell()
    if &l:spell
        set nospell
        echom "Spell OFF"
    else
        set spell spelllang=en_gb
        echom "Spell ON"
    endif
endfunction

" File templates
augroup templates
    autocmd!
    autocmd BufNewFile *.tex  0r ~/.vim/templates/skeleton.tex
    autocmd BufNewFile *.md   0r ~/.vim/templates/skeleton.md
augroup END

" vim-plug
call plug#begin('~/.local/share/nvim/plugged')

Plug 'xuhdev/vim-latex-live-preview', {'for': 'tex'}
    let g:livepreview_previewer = 'okular'
    set updatetime=1000

Plug 'leafgarland/typescript-vim', {'for': 'typescript'}

call plug#end()
